language: node_js
node_js:
  - "4"
  - "5"
  - "6"

sudo: false

# Install Python for schema validation
addons:
  apt:
    packages:
      - python
      - python-pip
      - python-virtualenv

# Install prerequisites for the schema validation
before_install:
  - virtualenv pyvalidator
  - source pyvalidator/bin/activate
  - pip install -r ./spec/requirements.txt

install:
  - npm install

script:
  - python ./spec/validate_question.py "./spec/schema_static.yml" "./example-quiz/"
  - npm run build
  - npm run doc
  - npm run coveralls
